### PR TITLE
Migrate legacy terms

### PR DESCRIPTION
**Pull request by brmscheiner**
Pull request checklist:
 - [x] Features and bugfixes should be PRed into the `develop` branch, **not** `main`
 - [x] All text is internationalized
 - [x] There are no linter errors
 - [x] New features support all states (loading, error, etc) 

Thanks for keeping it clean! Feel free to merge your own pull request after it has been approved - just use the "squash & merge" option.

### CODE REVIEW

**Review by Emily-Ke — APPROVED** [review]
Looks good to me.

**Review by Atticus29 — APPROVED** [review]
LGTM as well. Glad this is happening. I saw Occurrence the other day and was like, "Oh. We're still calling it that somewhere?". Nice.

**Comment by hwindsor** [comment]
Glad you approve. 
The one thing I will ask is that someone (other than me) actually QAs this properly. We really do not want this breaking things at this stage in the day.

**Comment by brmscheiner** [comment]
@hwindsor tested again (possibly retested? i cant remember if i already did it). anywho gonna click the button now

**Pull request merged**
