### PR TITLE
Dex 822 fix scroll

### PR DESCRIPTION
**Pull request by Atticus29**

### CODE REVIEW

**Review by Emily-Ke — COMMENTED** [review]
This fixes part of the problem, but the maxHeight prop may need to be supplied a different value for some of the Card instances.

**Comment by brmscheiner** [comment]
^agreed with @Emily-Ke. Also i found the original ticket that caused me to do overflow: scroll

https://wildme.atlassian.net/browse/DEX-797

Can you verify that this doesn't cause a regression for that issue? Testing multiple browsers could be good too, I never saw any of this stuff in chrome/brave

**Comment by Atticus29** [comment]
>

**Comment by Atticus29** [comment]
> ^agreed with @Emily-Ke. Also i found the original ticket that caused me to do overflow: scroll
> 
> https://wildme.atlassian.net/browse/DEX-797
> 
> Can you verify that this doesn't cause a regression for that issue? Testing multiple browsers could be good too, I never saw any of this stuff in chrome/brave

Confirmed. Note, however, that both in chrome and firefox, I have to two-finger scroll to even see the scrollbar there.
This felt very organic to me, but maybe not for all users? I don't know how to make the appearance of the horizontal scrollbar explicit? If that's even desired?

**Comment by brmscheiner** [comment]
Maybe `overflow-x`? Don't think it needs to be explicit as long as it works though

**Comment by Atticus29** [comment]
> 

Should I maybe do like a mouse hover x-overflow: scroll?

**Review by brmscheiner — APPROVED** [review]

**Pull request merged**
