### PR TITLE
Remove fake cooccurrences table

### PR DESCRIPTION
**Pull request by brmscheiner**
Doesn't look like this API will exist in time for MVP, so we are just going to comment out the table for now.

### CODE REVIEW

**Review by Atticus29 — APPROVED** [review]
LGTM

**Comment by colinwkingen** [comment]
For the record the API exists and is tested. I think we aren't going to spend the time to connect these dots this week though.

**Comment by Emily-Ke** [comment]
We should be able to delete the `fakeCoocs.js` file too then.

**Comment by brmscheiner** [comment]
@Emily-Ke I'm leaving the fake data for now so that when we uncomment it we can still see what we had before. I think it will be easier to develop that way.

**Pull request merged**
