### PR TITLE
Create a container image with the built code as wildme/codex-frontend

### PR DESCRIPTION
**Pull request by mmulich**

### CODE REVIEW

**Review by Emily-Ke — APPROVED** [review]
Looks ok as a temporary change.

**Review by brmscheiner — APPROVED** [review]
lgtm as much as i can understand it.. one thing, will running the script create files in the repo that need to be gitignored?

**Comment by mmulich** [comment]
> lgtm as much as i can understand it.. one thing, will running the script create files in the repo that need to be gitignored?

This won't create anything in the repo.

**Review by Atticus29 — APPROVED** [review]
Also lgtm

**Pull request merged**
